### PR TITLE
Added a paragraph and styled it

### PR DESCRIPTION
**Pull request by atmosfeer**
I just thought we needed another paragraph. What do you think of the color?

### CODE REVIEW

**Comment by atmosfeer** [comment]
What do you think @marcusjoost ?

**Comment by spamkanalen** [comment]
Color is awful. Why not red?

**Comment by marcusjoost** [comment]
this sucks dick

**Comment by atmosfeer** [comment]
Good point, I'll change it.

**Comment by marcusjoost** [comment]
make trump bigger

**Comment by marcusjoost** [comment]
Good job i like

**Pull request merged**
